export const infinitePaySourceUrls = [
  "https://www.infinitepay.io",
  "https://www.infinitepay.io/maquininha",
  "https://www.infinitepay.io/maquininha-celular",
  "https://www.infinitepay.io/tap-to-pay",
  "https://www.infinitepay.io/pdv",
  "https://www.infinitepay.io/receba-na-hora",
  "https://www.infinitepay.io/gestao-de-cobranca-2",
  "https://www.infinitepay.io/gestao-de-cobranca",
  "https://www.infinitepay.io/link-de-pagamento",
  "https://www.infinitepay.io/loja-online",
  "https://www.infinitepay.io/boleto",
  "https://www.infinitepay.io/conta-digital",
  "https://www.infinitepay.io/conta-pj",
  "https://www.infinitepay.io/pix",
  "https://www.infinitepay.io/pix-parcelado",
  "https://www.infinitepay.io/emprestimo",
  "https://www.infinitepay.io/cartao",
  "https://www.infinitepay.io/rendimento",
] as const;
